### PR TITLE
mini update UVR5_NO_UI.ipynb

### PR DESCRIPTION
**Pull request by Blane187**

### CODE REVIEW

**Comment by Eddycrack864** [comment]
Tysm for your contributions, the yt_dlp is very useful!

I will keep some of the changes and modify others.

**Review by Eddycrack864 — APPROVED** [review]
Tysm ❤️

**Comment by Eddycrack864** [comment]
Oh btw, I didn't change the installation using subprocess 'cause sometimes the download speed of colab is slow, so without output the user can't know it, while if the user sees the installation he can know if it is slow and restart the colab env.

**Comment by Blane187** [comment]
i see

**Pull request merged**
